const muiOutputRoot = 'ai-contract/packages/mui';

export default {
  schemaRoot: 'ai-contract/schema',
  readmePath: 'ai-contract/README.md',
  packages: {
    mui: {
      packageName: '@hugo-ui/mui',
      sourcePackagePath: 'packages/mui',
      packageJsonPath: 'packages/mui/package.json',
      publicEntry: 'packages/mui/src/index.ts',
      tsconfigPath: 'packages/mui/tsconfig.json',
      sourceRoot: 'packages/mui/src',
      outputRoot: muiOutputRoot,
      componentOutputDir: `${muiOutputRoot}/components`,
      metadataDir: `${muiOutputRoot}/metadata/components`,
      metadataRoot: `${muiOutputRoot}/metadata`,
      tokenOutputDir: `${muiOutputRoot}/tokens`,
      tokenContract: 'tokens/token-map.contract.json',
      tokenSources: {
        rawPalette: 'packages/mui/src/styles/color.ts',
        semanticColorRoles: 'packages/mui/src/styles/colorRoles.ts',
        theme: 'packages/mui/src/styles/theme.ts',
      },
      semanticColorRolesExportName: 'hugoUIColorRoles',
      tokenThemeExposures: [
        {
          name: 'hugoUITheme.hugoUIColors',
          source: 'packages/mui/src/styles/theme.ts',
          mapsFrom: 'packages/mui/src/styles/color.ts',
        },
        {
          name: 'hugoUITheme.hugoUIColorRoles',
          source: 'packages/mui/src/styles/theme.ts',
          mapsFrom: 'packages/mui/src/styles/colorRoles.ts',
        },
      ],
      manifestNotes: [
        'This manifest covers only the MUI package scope.',
        'Use the component contract files as the machine-readable entry points for AI generation and validation.',
      ],
      artifactNamePrefix: 'hugo-ui-mui-ai-contract',
      artifactFormat: 'hugo-ui-mui-ai-contract/v1',
      artifactOutputDir: 'dist/ai-contract',
      tagPattern: 'mui-ai-contract-v*',
      forbiddenPatterns: ['@hugo-ui/shadcn', 'packages/shadcn', '@demo/design-system'],
      components: [
        {
          componentName: 'Button',
          importName: 'Button',
          implementationName: 'HugoUIButton',
          propsTypeName: 'HugoUIButtonProps',
          sourceFile: 'packages/mui/src/Button/Button.tsx',
          componentIndexFile: 'packages/mui/src/Button/index.ts',
          sourceFiles: [
            'packages/mui/src/Button/Button.tsx',
            'packages/mui/src/Button/buttonTypes.ts',
            'packages/mui/src/Button/index.ts',
            'packages/mui/src/Button/styles/buttonTokens.ts',
            'packages/mui/src/Button/button.test.tsx',
            'packages/storybook/src/stories/Button.stories.tsx',
          ],
          directTypeNames: [
            'HugoUIButtonProps',
            'HugoUIButtonCommonProps',
            'HugoUIButtonStyleProps',
            'HugoUIPrimaryButtonStyleProps',
            'HugoUIPrimaryButtonProps',
            'HugoUISecondaryButtonStyleProps',
            'HugoUISecondaryButtonProps',
            'HugoUITertiaryButtonStyleProps',
            'HugoUITertiaryButtonProps',
            'HugoUIDestructButtonStyleProps',
            'HugoUIDestructButtonProps',
          ],
          relatedTypes: [
            'HugoUIButtonCommonProps',
            'HugoUIPrimaryButtonProps',
            'HugoUISecondaryButtonProps',
            'HugoUITertiaryButtonProps',
            'HugoUIDestructButtonProps',
          ],
          trackedProps: [
            'children',
            'level',
            'colorTheme',
            'size',
            'loading',
            'loadingPosition',
            'labelHidden',
            'disabled',
            'startIcon',
            'endIcon',
            'fullWidth',
            'type',
            'onClick',
            'href',
            'target',
            'rel',
            'tabIndex',
            'className',
            'style',
            'sx',
            'component',
          ],
          typeFromValuesProps: ['level', 'colorTheme', 'size', 'loadingPosition'],
        },
        {
          componentName: 'Input',
          importName: 'Input',
          implementationName: 'HugoUIInput',
          propsTypeName: 'HugoUIInputProps',
          sourceFile: 'packages/mui/src/Input/Input.tsx',
          componentIndexFile: 'packages/mui/src/Input/index.ts',
          sourceFiles: [
            'packages/mui/src/Input/Input.tsx',
            'packages/mui/src/Input/InputStatus.tsx',
            'packages/mui/src/Input/index.ts',
            'packages/mui/src/Input/styles/inputTokens.ts',
            'packages/mui/src/Input/input.test.tsx',
            'packages/storybook/src/stories/Input.stories.tsx',
          ],
          directTypeNames: [
            'HugoUIInputProps',
            'HugoUIInputExtraProps',
            'HugoUIInputCompatibilityProps',
          ],
          relatedTypes: ['HugoUIInputExtraProps', 'HugoUIInputCompatibilityProps'],
          trackedProps: [
            'id',
            'label',
            'value',
            'helperText',
            'extraMessage',
            'color',
            'mini',
            'loading',
            'showCount',
            'multiline',
            'required',
            'disabled',
            'fullWidth',
            'icon',
            'placeholder',
            'autoFocus',
            'autoFocusByKeyboard',
            'name',
            'type',
            'onChange',
            'onBlur',
            'InputProps',
            'inputProps',
            'InputLabelProps',
            'slotProps',
            'inputRef',
            'className',
            'style',
            'sx',
          ],
          typeFromValuesProps: [],
        },
        {
          componentName: 'Modal',
          importName: 'Modal',
          implementationName: 'HugoUIModal',
          propsTypeName: 'HugoUIModalProps',
          sourceFile: 'packages/mui/src/Modal/Modal.tsx',
          componentIndexFile: 'packages/mui/src/Modal/index.ts',
          sourceFiles: [
            'packages/mui/src/Modal/Modal.tsx',
            'packages/mui/src/Modal/ModalFooter.tsx',
            'packages/mui/src/Modal/ModalTitle.tsx',
            'packages/mui/src/Modal/Feedback.tsx',
            'packages/mui/src/Modal/index.ts',
            'packages/mui/src/Modal/styles/modalTokens.ts',
            'packages/mui/src/Modal/Modal.test.tsx',
            'packages/mui/src/Modal/ModalFooter.test.tsx',
            'packages/mui/src/Modal/ModalTitle.test.tsx',
            'packages/storybook/src/stories/Modal.stories.tsx',
          ],
          directTypeNames: ['HugoUIModalProps'],
          relatedTypes: [
            'HugoUIModalButtonsType',
            'HugoUIModalPrimaryButtonProps',
            'HugoUIModalSecondaryButtonProps',
            'HugoUIModalTertiaryButtonProps',
            'HugoUIFeedbackMessageType',
          ],
          trackedProps: [
            'open',
            'title',
            'type',
            'onClose',
            'buttonDefs',
            'children',
            'subTitle',
            'closeButton',
            'footerComponent',
            'headerComponent',
            'loading',
            'showLoadingIndicator',
            'messages',
            'headerPrefixIcon',
            'disableAutoFocus',
            'id',
            'className',
            'style',
            'slots',
            'transitionDuration',
            'fullScreen',
          ],
          typeFromValuesProps: ['type'],
        },
      ],
    },
  },
};
